export const resources = [
  {
    href: "/company-data",
    text: "Company Data",
  },
  {
    href: "/recipe-finder",
    text: "Recipe Finder",
  },
  {
    href: "/weather-recommender",
    text: "Weather Recommender",
  },
];

export const aisleCategories = [
  "Baking",
  "Health Foods",
  "Spices and Seasonings",
  "Pasta and Rice",
  "Bakery/Bread",
  "Refrigerated",
  "Canned and Jarred",
  "Frozen",
  "Nut butters, Jams, and Honey",
  "Oil, Vinegar, Salad Dressing",
  "Condiments",
  "Savory Snacks",
  "Milk, Eggs, Other Dairy",
  "Ethnic Foods",
  "Tea and Coffee",
  "Meat",
  "Gourmet",
  "Sweet Snacks",
  "Gluten Free",
  "Alcoholic Beverages",
  "Cereal",
  "Nuts",
  "Beverages",
  "Produce",
  "Not in Grocery Store/Homemade",
  "Seafood",
  "Cheese",
  "Dried Fruits",
  "Online",
  "Grilling Supplies",
  "Bread",
];
